name = "daxlinks-webhook"
main = "webhook.js"
compatibility_date = "2025-11-08"

# Cloudflare account for daxlinksonline.link
account_id = "beda455cdcb069b4d415c7eb817ecb46"

[vars]
ORIGIN_URL = "https://api.daxlinksonline.link"

# Optional: manage routes here or add them via the Cloudflare dashboard
# routes = ["*.daxlinksonline.link/webhook"]
# routes = ["*.daxlinksonline.link/webhook"]
